"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
#DATA_FILES = ['./static', './lib']
OPTIONS = {'argv_emulation': True,
           'includes': ['tornado.*'],}

setup(
    app=APP,
    #data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    package='static',
    package_dir={'', './'}
)
